### PR TITLE
Fixes some typos in Lesson 4 pages

### PR DESCRIPTION
**Pull request by hosungs**
Tried to fix some typos in Lesson 4 pages as I was rereading them.

### CODE REVIEW

**Comment by PythonCHB** [comment]
Thanks! I think there are some RST formatting issues still, but I'll check that out after merging.

Are you set up to to build the docs to see how they render? that would be helpful. And if you like, I can give you permissions to re-render the published version as well. I think it's good to have a PR for substantive changes, but for typos, might as well just publish them.

**Comment by PythonCHB** [comment]
OK -- I've fixed some RST, and updated the pages a bit.

(also added an optional Unicode page...)

**Comment by hosungs** [comment]
@PythonCHB -- Yes, I can run `make.bat` on my git bash cmdline to build HTMLs. I just get lazy with that step... Sorry about that. Sure, I'd be happy to just commit any typo fixes directly, without PRs. Thanks!

**Comment by PythonCHB** [comment]
OK -- I've invited you to the team -- welcome aboard!

-CHB

**Pull request merged**
