### PR TITLE
Feature Branching Doc

### PR DESCRIPTION
**Pull request by natasha-aleksandrova**
@PythonCHB let me know if you would like me to organize images differently, also I couldn't get the images to scale right (some are too large, and would like them smaller).

### CODE REVIEW

**Comment by PythonCHB** [comment]
taking a look now.

Did you run this through Sphinx? I'm getting a lot of errors.

You should be able to do it with:

`make html`

In the root dir of the repo

I'm going to try to fix the easy stuff now, and then see how it goes.

-CHB

**Comment by natasha-aleksandrova** [comment]
No, I have never worked with Sphinx documentation so not really sure about all the steps.

I thought it just needed to be .rst valid.

**Comment by PythonCHB** [comment]
Well, Sphinx is rst, so that's the start, but it also builds up a while network of pages, and cross referencing, and all that, so there does need to be some structure to it.

I'm almost done fixing it up -- only minor changes, really.

I'll push my changes soon.

**Comment by natasha-aleksandrova** [comment]
gotcha, thanks Chris!

**Comment by PythonCHB** [comment]
OK -- got it all cleaned up.

Sizing images is a pain in RST/Sphinx (but then, sizing images is a pain everywhere else, too!), but it looks like using `:scale: 50`. Does a pretty good job.

If you don't like that, we could try a different scale, or set:

`:width: 400px`

or

`:width: 4in`

or something.

But this is readable at least :-)

It should be published on gitHub.io here:

https://uwpce-pythoncert.github.io/PythonCertDevel/supplemental/dev_environment/feature_branching.html

So you can take a look and see what else it needs, and point your students to it if you think it's ready.

**Comment by PythonCHB** [comment]
Oh, and it should also be referenced from this page:

https://uwpce-pythoncert.github.io/PythonCertDevel/supplemental/dev_environment/index.html

**Comment by natasha-aleksandrova** [comment]
yay! Thanks looks great 🙂

**Pull request merged**
