### PR TITLE
add more to file writing section

### PR DESCRIPTION
**Pull request by natasha-aleksandrova**
ended up also adding `Convert your main donor data structure to be a dict.` - I still get occasional students that don't change main data structure to be a dictionary.

the rest are updates for file writing:
* mentioned hard coded paths - I get a ton of those
* tempfile - I think a cool option to learn and in general a good library to be aware of

### CODE REVIEW

**Comment by natasha-aleksandrova** [comment]
[Mailroom - lesson4 - file writing](https://trello.com/c/aIwjs6r3/7-mailroom-lesson4-file-writing)

**Comment by natasha-aleksandrova** [comment]
[Mailroom - lesson4 - file writing](https://trello.com/c/aIwjs6r3/7-mailroom-lesson4-file-writing)

**Comment by natasha-aleksandrova** [comment]
@PythonCHB flagging as a reminder 🙂

**Comment by PythonCHB** [comment]
LGTM -- And we're getting review on the mailroom assignment in another PR as well, so I'll merge and we can move on.

-CHB

**Pull request merged**
