### PR TITLE
Html tutorial review

### PR DESCRIPTION
**Pull request by UWEditor**

### CODE REVIEW

**Comment by PythonCHB** [comment]
Looking good -- thanks!

**Comment by PythonCHB** [comment]
@natasha-aleksandrova -- what's the plan for bringing this in to c_1_revision ?

**Comment by natasha-aleksandrova** [comment]
per my message in slack this was supposed to be merged into `c_1_revision`.

the target branch is wrong here and shouldn't have been merged; sounds you will need to merge this into the correct branch.

**Comment by PythonCHB** [comment]
I was wondering....

I'll clean that up now.

**Comment by PythonCHB** [comment]
OK, all merged into c_1_revision

**Pull request merged**
